
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("648d4b04-dcd3-4a4a-9567-3c327345c3d0")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("TTMS", "departmentuser", "department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(department), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(user), True)>
<Assembly: EdmRelationshipAttribute("TTMS", "userleveluser", "userlevel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(userlevel), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(user), True)>
<Assembly: EdmRelationshipAttribute("TTMS", "userncr", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(user), "ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ncr), True)>
<Assembly: EdmRelationshipAttribute("TTMS", "userncr1", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(user), "ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ncr), True)>
<Assembly: EdmRelationshipAttribute("TTMS", "userncr2", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(user), "ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ncr), True)>
<Assembly: EdmRelationshipAttribute("TTMS", "ncrcc", "ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ncr), "cc", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Cc), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class rqtsEntities1
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new rqtsEntities1 object using the connection string found in the 'rqtsEntities1' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=rqtsEntities1", "rqtsEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rqtsEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "rqtsEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rqtsEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "rqtsEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property departments() As ObjectSet(Of department)
        Get
            If (_departments Is Nothing) Then
                _departments = MyBase.CreateObjectSet(Of department)("departments")
            End If
            Return _departments
        End Get
    End Property

    Private _departments As ObjectSet(Of department)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ncrs() As ObjectSet(Of ncr)
        Get
            If (_ncrs Is Nothing) Then
                _ncrs = MyBase.CreateObjectSet(Of ncr)("ncrs")
            End If
            Return _ncrs
        End Get
    End Property

    Private _ncrs As ObjectSet(Of ncr)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property notifications() As ObjectSet(Of notification)
        Get
            If (_notifications Is Nothing) Then
                _notifications = MyBase.CreateObjectSet(Of notification)("notifications")
            End If
            Return _notifications
        End Get
    End Property

    Private _notifications As ObjectSet(Of notification)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property users() As ObjectSet(Of user)
        Get
            If (_users Is Nothing) Then
                _users = MyBase.CreateObjectSet(Of user)("users")
            End If
            Return _users
        End Get
    End Property

    Private _users As ObjectSet(Of user)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property userlevels() As ObjectSet(Of userlevel)
        Get
            If (_userlevels Is Nothing) Then
                _userlevels = MyBase.CreateObjectSet(Of userlevel)("userlevels")
            End If
            Return _userlevels
        End Get
    End Property

    Private _userlevels As ObjectSet(Of userlevel)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ccitems() As ObjectSet(Of ccitem)
        Get
            If (_ccitems Is Nothing) Then
                _ccitems = MyBase.CreateObjectSet(Of ccitem)("ccitems")
            End If
            Return _ccitems
        End Get
    End Property

    Private _ccitems As ObjectSet(Of ccitem)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Ccs() As ObjectSet(Of Cc)
        Get
            If (_Ccs Is Nothing) Then
                _Ccs = MyBase.CreateObjectSet(Of Cc)("Ccs")
            End If
            Return _Ccs
        End Get
    End Property

    Private _Ccs As ObjectSet(Of Cc)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the departments EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTodepartments(ByVal department As department)
        MyBase.AddObject("departments", department)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ncrs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToncrs(ByVal ncr As ncr)
        MyBase.AddObject("ncrs", ncr)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the notifications EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTonotifications(ByVal notification As notification)
        MyBase.AddObject("notifications", notification)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTousers(ByVal user As user)
        MyBase.AddObject("users", user)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the userlevels EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTouserlevels(ByVal userlevel As userlevel)
        MyBase.AddObject("userlevels", userlevel)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ccitems EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToccitems(ByVal ccitem As ccitem)
        MyBase.AddObject("ccitems", ccitem)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Ccs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCcs(ByVal cc As Cc)
        MyBase.AddObject("Ccs", cc)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TTMS", Name:="Cc")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Cc
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Cc object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="ccdone">Initial value of the ccdone property.</param>
    ''' <param name="ncr_id">Initial value of the ncr_id property.</param>
    Public Shared Function CreateCc(id As Global.System.Int32, ccdone As Global.System.SByte, ncr_id As Global.System.Int32) As Cc
        Dim cc as Cc = New Cc
        cc.id = id
        cc.ccdone = ccdone
        cc.ncr_id = ncr_id
        Return cc
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ccdone() As Global.System.SByte
        Get
            Return _ccdone
        End Get
        Set
            OnccdoneChanging(value)
            ReportPropertyChanging("ccdone")
            _ccdone = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ccdone")
            OnccdoneChanged()
        End Set
    End Property

    Private _ccdone As Global.System.SByte
    Private Partial Sub OnccdoneChanging(value As Global.System.SByte)
    End Sub

    Private Partial Sub OnccdoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ncr_id() As Global.System.Int32
        Get
            Return _ncr_id
        End Get
        Set
            Onncr_idChanging(value)
            ReportPropertyChanging("ncr_id")
            _ncr_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ncr_id")
            Onncr_idChanged()
        End Set
    End Property

    Private _ncr_id As Global.System.Int32
    Private Partial Sub Onncr_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onncr_idChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "ncrcc", "ncr")>
    Public Property ncr() As ncr
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ncr)("TTMS.ncrcc", "ncr").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ncr)("TTMS.ncrcc", "ncr").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ncrReference() As EntityReference(Of ncr)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ncr)("TTMS.ncrcc", "ncr")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ncr)("TTMS.ncrcc", "ncr", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TTMS", Name:="ccitem")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ccitem
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ccitem object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="action">Initial value of the action property.</param>
    ''' <param name="actionby_id">Initial value of the actionby_id property.</param>
    ''' <param name="duedate">Initial value of the duedate property.</param>
    ''' <param name="status">Initial value of the status property.</param>
    ''' <param name="cc_id">Initial value of the cc_id property.</param>
    ''' <param name="corrective">Initial value of the corrective property.</param>
    Public Shared Function Createccitem(id As Global.System.Int32, action As Global.System.String, actionby_id As Global.System.Int32, duedate As Global.System.DateTime, status As Global.System.String, cc_id As Global.System.Int32, corrective As Global.System.String) As ccitem
        Dim ccitem as ccitem = New ccitem
        ccitem.id = id
        ccitem.action = action
        ccitem.actionby_id = actionby_id
        ccitem.duedate = duedate
        ccitem.status = status
        ccitem.cc_id = cc_id
        ccitem.corrective = corrective
        Return ccitem
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property action() As Global.System.String
        Get
            Return _action
        End Get
        Set
            OnactionChanging(value)
            ReportPropertyChanging("action")
            _action = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("action")
            OnactionChanged()
        End Set
    End Property

    Private _action As Global.System.String
    Private Partial Sub OnactionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnactionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property actionby_id() As Global.System.Int32
        Get
            Return _actionby_id
        End Get
        Set
            Onactionby_idChanging(value)
            ReportPropertyChanging("actionby_id")
            _actionby_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("actionby_id")
            Onactionby_idChanged()
        End Set
    End Property

    Private _actionby_id As Global.System.Int32
    Private Partial Sub Onactionby_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onactionby_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property duedate() As Global.System.DateTime
        Get
            Return _duedate
        End Get
        Set
            OnduedateChanging(value)
            ReportPropertyChanging("duedate")
            _duedate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("duedate")
            OnduedateChanged()
        End Set
    End Property

    Private _duedate As Global.System.DateTime
    Private Partial Sub OnduedateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnduedateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property completiondate() As Nullable(Of Global.System.DateTime)
        Get
            Return _completiondate
        End Get
        Set
            OncompletiondateChanging(value)
            ReportPropertyChanging("completiondate")
            _completiondate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("completiondate")
            OncompletiondateChanged()
        End Set
    End Property

    Private _completiondate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OncompletiondateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OncompletiondateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status() As Global.System.String
        Get
            Return _status
        End Get
        Set
            OnstatusChanging(value)
            ReportPropertyChanging("status")
            _status = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("status")
            OnstatusChanged()
        End Set
    End Property

    Private _status As Global.System.String
    Private Partial Sub OnstatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cc_id() As Global.System.Int32
        Get
            Return _cc_id
        End Get
        Set
            Oncc_idChanging(value)
            ReportPropertyChanging("cc_id")
            _cc_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cc_id")
            Oncc_idChanged()
        End Set
    End Property

    Private _cc_id As Global.System.Int32
    Private Partial Sub Oncc_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Oncc_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property passed() As Nullable(Of Global.System.Boolean)
        Get
            Return _passed
        End Get
        Set
            OnpassedChanging(value)
            ReportPropertyChanging("passed")
            _passed = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("passed")
            OnpassedChanged()
        End Set
    End Property

    Private _passed As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnpassedChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnpassedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property failed() As Nullable(Of Global.System.Boolean)
        Get
            Return _failed
        End Get
        Set
            OnfailedChanging(value)
            ReportPropertyChanging("failed")
            _failed = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("failed")
            OnfailedChanged()
        End Set
    End Property

    Private _failed As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnfailedChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnfailedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property reviewer_id() As Nullable(Of Global.System.Int32)
        Get
            Return _reviewer_id
        End Get
        Set
            Onreviewer_idChanging(value)
            ReportPropertyChanging("reviewer_id")
            _reviewer_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("reviewer_id")
            Onreviewer_idChanged()
        End Set
    End Property

    Private _reviewer_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onreviewer_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onreviewer_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property reviewdate() As Nullable(Of Global.System.DateTime)
        Get
            Return _reviewdate
        End Get
        Set
            OnreviewdateChanging(value)
            ReportPropertyChanging("reviewdate")
            _reviewdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("reviewdate")
            OnreviewdateChanged()
        End Set
    End Property

    Private _reviewdate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnreviewdateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnreviewdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property reviewcomment() As Global.System.String
        Get
            Return _reviewcomment
        End Get
        Set
            OnreviewcommentChanging(value)
            ReportPropertyChanging("reviewcomment")
            _reviewcomment = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("reviewcomment")
            OnreviewcommentChanged()
        End Set
    End Property

    Private _reviewcomment As Global.System.String
    Private Partial Sub OnreviewcommentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnreviewcommentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property corrective() As Global.System.String
        Get
            Return _corrective
        End Get
        Set
            OncorrectiveChanging(value)
            ReportPropertyChanging("corrective")
            _corrective = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("corrective")
            OncorrectiveChanged()
        End Set
    End Property

    Private _corrective As Global.System.String
    Private Partial Sub OncorrectiveChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncorrectiveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TTMS", Name:="department")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class department
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new department object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    Public Shared Function Createdepartment(id As Global.System.Int32, description As Global.System.String) As department
        Dim department as department = New department
        department.id = id
        department.description = description
        Return department
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "departmentuser", "user")>
     Public Property users() As EntityCollection(Of user)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of user)("TTMS.departmentuser", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of user)("TTMS.departmentuser", "user", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TTMS", Name:="ncr")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ncr
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ncr object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="raisedby_id">Initial value of the raisedby_id property.</param>
    ''' <param name="status_id">Initial value of the status_id property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    ''' <param name="title">Initial value of the title property.</param>
    Public Shared Function Createncr(id As Global.System.Int32, raisedby_id As Global.System.Int32, status_id As Global.System.Int32, description As Global.System.String, title As Global.System.String) As ncr
        Dim ncr as ncr = New ncr
        ncr.id = id
        ncr.raisedby_id = raisedby_id
        ncr.status_id = status_id
        ncr.description = description
        ncr.title = title
        Return ncr
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property raisedby_id() As Global.System.Int32
        Get
            Return _raisedby_id
        End Get
        Set
            Onraisedby_idChanging(value)
            ReportPropertyChanging("raisedby_id")
            _raisedby_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("raisedby_id")
            Onraisedby_idChanged()
        End Set
    End Property

    Private _raisedby_id As Global.System.Int32
    Private Partial Sub Onraisedby_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onraisedby_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property assignedto_id() As Nullable(Of Global.System.Int32)
        Get
            Return _assignedto_id
        End Get
        Set
            Onassignedto_idChanging(value)
            ReportPropertyChanging("assignedto_id")
            _assignedto_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("assignedto_id")
            Onassignedto_idChanged()
        End Set
    End Property

    Private _assignedto_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onassignedto_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onassignedto_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property delegatedto_id() As Nullable(Of Global.System.Int32)
        Get
            Return _delegatedto_id
        End Get
        Set
            Ondelegatedto_idChanging(value)
            ReportPropertyChanging("delegatedto_id")
            _delegatedto_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delegatedto_id")
            Ondelegatedto_idChanged()
        End Set
    End Property

    Private _delegatedto_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Ondelegatedto_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Ondelegatedto_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property raiseddate() As Nullable(Of Global.System.DateTime)
        Get
            Return _raiseddate
        End Get
        Set
            OnraiseddateChanging(value)
            ReportPropertyChanging("raiseddate")
            _raiseddate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("raiseddate")
            OnraiseddateChanged()
        End Set
    End Property

    Private _raiseddate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnraiseddateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnraiseddateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status_id() As Global.System.Int32
        Get
            Return _status_id
        End Get
        Set
            Onstatus_idChanging(value)
            ReportPropertyChanging("status_id")
            _status_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("status_id")
            Onstatus_idChanged()
        End Set
    End Property

    Private _status_id As Global.System.Int32
    Private Partial Sub Onstatus_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstatus_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cc_id() As Nullable(Of Global.System.Int32)
        Get
            Return _cc_id
        End Get
        Set
            Oncc_idChanging(value)
            ReportPropertyChanging("cc_id")
            _cc_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cc_id")
            Oncc_idChanged()
        End Set
    End Property

    Private _cc_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncc_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncc_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property rcp_id() As Nullable(Of Global.System.Int32)
        Get
            Return _rcp_id
        End Get
        Set
            Onrcp_idChanging(value)
            ReportPropertyChanging("rcp_id")
            _rcp_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("rcp_id")
            Onrcp_idChanged()
        End Set
    End Property

    Private _rcp_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onrcp_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onrcp_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property title() As Global.System.String
        Get
            Return _title
        End Get
        Set
            OntitleChanging(value)
            ReportPropertyChanging("title")
            _title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("title")
            OntitleChanged()
        End Set
    End Property

    Private _title As Global.System.String
    Private Partial Sub OntitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntitleChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userncr", "user")>
    Public Property RaisedBy() As user
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr", "user").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr", "user").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property RaisedByReference() As EntityReference(Of user)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of user)("TTMS.userncr", "user", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userncr1", "user")>
    Public Property DelegatedTo() As user
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr1", "user").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr1", "user").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DelegatedToReference() As EntityReference(Of user)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr1", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of user)("TTMS.userncr1", "user", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userncr2", "user")>
    Public Property AssignedTo() As user
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr2", "user").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr2", "user").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AssignedToReference() As EntityReference(Of user)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("TTMS.userncr2", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of user)("TTMS.userncr2", "user", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "ncrcc", "cc")>
    Public Property ccs() As Cc
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cc)("TTMS.ncrcc", "cc").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cc)("TTMS.ncrcc", "cc").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ccsReference() As EntityReference(Of Cc)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cc)("TTMS.ncrcc", "cc")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Cc)("TTMS.ncrcc", "cc", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TTMS", Name:="notification")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class notification
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new notification object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="user_id">Initial value of the user_id property.</param>
    ''' <param name="ncr_id">Initial value of the ncr_id property.</param>
    ''' <param name="message">Initial value of the message property.</param>
    ''' <param name="timestamp">Initial value of the timestamp property.</param>
    Public Shared Function Createnotification(id As Global.System.Int32, user_id As Global.System.Int32, ncr_id As Global.System.Int32, message As Global.System.String, timestamp As Global.System.DateTime) As notification
        Dim notification as notification = New notification
        notification.id = id
        notification.user_id = user_id
        notification.ncr_id = ncr_id
        notification.message = message
        notification.timestamp = timestamp
        Return notification
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property user_id() As Global.System.Int32
        Get
            Return _user_id
        End Get
        Set
            Onuser_idChanging(value)
            ReportPropertyChanging("user_id")
            _user_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("user_id")
            Onuser_idChanged()
        End Set
    End Property

    Private _user_id As Global.System.Int32
    Private Partial Sub Onuser_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onuser_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ncr_id() As Global.System.Int32
        Get
            Return _ncr_id
        End Get
        Set
            Onncr_idChanging(value)
            ReportPropertyChanging("ncr_id")
            _ncr_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ncr_id")
            Onncr_idChanged()
        End Set
    End Property

    Private _ncr_id As Global.System.Int32
    Private Partial Sub Onncr_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onncr_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property message() As Global.System.String
        Get
            Return _message
        End Get
        Set
            OnmessageChanging(value)
            ReportPropertyChanging("message")
            _message = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("message")
            OnmessageChanged()
        End Set
    End Property

    Private _message As Global.System.String
    Private Partial Sub OnmessageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmessageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property timestamp() As Global.System.DateTime
        Get
            Return _timestamp
        End Get
        Set
            OntimestampChanging(value)
            ReportPropertyChanging("timestamp")
            _timestamp = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("timestamp")
            OntimestampChanged()
        End Set
    End Property

    Private _timestamp As Global.System.DateTime
    Private Partial Sub OntimestampChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OntimestampChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TTMS", Name:="user")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class user
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new user object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="firstname">Initial value of the firstname property.</param>
    ''' <param name="surname">Initial value of the surname property.</param>
    ''' <param name="userid">Initial value of the userid property.</param>
    ''' <param name="active">Initial value of the active property.</param>
    ''' <param name="level_id">Initial value of the level_id property.</param>
    ''' <param name="department_id">Initial value of the department_id property.</param>
    ''' <param name="password">Initial value of the password property.</param>
    ''' <param name="admin">Initial value of the admin property.</param>
    Public Shared Function Createuser(id As Global.System.Int32, firstname As Global.System.String, surname As Global.System.String, userid As Global.System.String, active As Global.System.SByte, level_id As Global.System.Int32, department_id As Global.System.Int32, password As Global.System.String, admin As Global.System.SByte) As user
        Dim user as user = New user
        user.id = id
        user.firstname = firstname
        user.surname = surname
        user.userid = userid
        user.active = active
        user.level_id = level_id
        user.department_id = department_id
        user.password = password
        user.admin = admin
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property firstname() As Global.System.String
        Get
            Return _firstname
        End Get
        Set
            OnfirstnameChanging(value)
            ReportPropertyChanging("firstname")
            _firstname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("firstname")
            OnfirstnameChanged()
        End Set
    End Property

    Private _firstname As Global.System.String
    Private Partial Sub OnfirstnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfirstnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property surname() As Global.System.String
        Get
            Return _surname
        End Get
        Set
            OnsurnameChanging(value)
            ReportPropertyChanging("surname")
            _surname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("surname")
            OnsurnameChanged()
        End Set
    End Property

    Private _surname As Global.System.String
    Private Partial Sub OnsurnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsurnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property userid() As Global.System.String
        Get
            Return _userid
        End Get
        Set
            OnuseridChanging(value)
            ReportPropertyChanging("userid")
            _userid = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("userid")
            OnuseridChanged()
        End Set
    End Property

    Private _userid As Global.System.String
    Private Partial Sub OnuseridChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnuseridChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property email() As Global.System.String
        Get
            Return _email
        End Get
        Set
            OnemailChanging(value)
            ReportPropertyChanging("email")
            _email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("email")
            OnemailChanged()
        End Set
    End Property

    Private _email As Global.System.String
    Private Partial Sub OnemailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnemailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property active() As Global.System.SByte
        Get
            Return _active
        End Get
        Set
            OnactiveChanging(value)
            ReportPropertyChanging("active")
            _active = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("active")
            OnactiveChanged()
        End Set
    End Property

    Private _active As Global.System.SByte
    Private Partial Sub OnactiveChanging(value As Global.System.SByte)
    End Sub

    Private Partial Sub OnactiveChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property level_id() As Global.System.Int32
        Get
            Return _level_id
        End Get
        Set
            Onlevel_idChanging(value)
            ReportPropertyChanging("level_id")
            _level_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("level_id")
            Onlevel_idChanged()
        End Set
    End Property

    Private _level_id As Global.System.Int32
    Private Partial Sub Onlevel_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onlevel_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property department_id() As Global.System.Int32
        Get
            Return _department_id
        End Get
        Set
            Ondepartment_idChanging(value)
            ReportPropertyChanging("department_id")
            _department_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("department_id")
            Ondepartment_idChanged()
        End Set
    End Property

    Private _department_id As Global.System.Int32
    Private Partial Sub Ondepartment_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondepartment_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property admin() As Global.System.SByte
        Get
            Return _admin
        End Get
        Set
            OnadminChanging(value)
            ReportPropertyChanging("admin")
            _admin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("admin")
            OnadminChanged()
        End Set
    End Property

    Private _admin As Global.System.SByte
    Private Partial Sub OnadminChanging(value As Global.System.SByte)
    End Sub

    Private Partial Sub OnadminChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "departmentuser", "department")>
    Public Property department() As department
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of department)("TTMS.departmentuser", "department").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of department)("TTMS.departmentuser", "department").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property departmentReference() As EntityReference(Of department)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of department)("TTMS.departmentuser", "department")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of department)("TTMS.departmentuser", "department", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userleveluser", "userlevel")>
    Public Property userlevel() As userlevel
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of userlevel)("TTMS.userleveluser", "userlevel").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of userlevel)("TTMS.userleveluser", "userlevel").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property userlevelReference() As EntityReference(Of userlevel)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of userlevel)("TTMS.userleveluser", "userlevel")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of userlevel)("TTMS.userleveluser", "userlevel", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userncr", "ncr")>
     Public Property ncrs() As EntityCollection(Of ncr)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ncr)("TTMS.userncr", "ncr")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ncr)("TTMS.userncr", "ncr", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userncr1", "ncr")>
     Public Property ncrs_1() As EntityCollection(Of ncr)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ncr)("TTMS.userncr1", "ncr")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ncr)("TTMS.userncr1", "ncr", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userncr2", "ncr")>
     Public Property ncrs_2() As EntityCollection(Of ncr)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ncr)("TTMS.userncr2", "ncr")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ncr)("TTMS.userncr2", "ncr", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TTMS", Name:="userlevel")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class userlevel
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new userlevel object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createuserlevel(id As Global.System.Int32) As userlevel
        Dim userlevel as userlevel = New userlevel
        userlevel.id = id
        Return userlevel
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fulldescription() As Global.System.String
        Get
            Return _fulldescription
        End Get
        Set
            OnfulldescriptionChanging(value)
            ReportPropertyChanging("fulldescription")
            _fulldescription = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fulldescription")
            OnfulldescriptionChanged()
        End Set
    End Property

    Private _fulldescription As Global.System.String
    Private Partial Sub OnfulldescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfulldescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property shortdescription() As Global.System.String
        Get
            Return _shortdescription
        End Get
        Set
            OnshortdescriptionChanging(value)
            ReportPropertyChanging("shortdescription")
            _shortdescription = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("shortdescription")
            OnshortdescriptionChanged()
        End Set
    End Property

    Private _shortdescription As Global.System.String
    Private Partial Sub OnshortdescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnshortdescriptionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("TTMS", "userleveluser", "user")>
     Public Property users() As EntityCollection(Of user)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of user)("TTMS.userleveluser", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of user)("TTMS.userleveluser", "user", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


