
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("e8983c43-4e6d-43ae-b878-6f5e3b323220")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class rqtsEntities1
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new rqtsEntities1 object using the connection string found in the 'rqtsEntities1' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=rqtsEntities1", "rqtsEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rqtsEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "rqtsEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rqtsEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "rqtsEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property departments() As ObjectSet(Of department)
        Get
            If (_departments Is Nothing) Then
                _departments = MyBase.CreateObjectSet(Of department)("departments")
            End If
            Return _departments
        End Get
    End Property

    Private _departments As ObjectSet(Of department)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ncrs() As ObjectSet(Of ncr)
        Get
            If (_ncrs Is Nothing) Then
                _ncrs = MyBase.CreateObjectSet(Of ncr)("ncrs")
            End If
            Return _ncrs
        End Get
    End Property

    Private _ncrs As ObjectSet(Of ncr)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property notifications() As ObjectSet(Of notification)
        Get
            If (_notifications Is Nothing) Then
                _notifications = MyBase.CreateObjectSet(Of notification)("notifications")
            End If
            Return _notifications
        End Get
    End Property

    Private _notifications As ObjectSet(Of notification)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property users() As ObjectSet(Of user)
        Get
            If (_users Is Nothing) Then
                _users = MyBase.CreateObjectSet(Of user)("users")
            End If
            Return _users
        End Get
    End Property

    Private _users As ObjectSet(Of user)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property userlevels() As ObjectSet(Of userlevel)
        Get
            If (_userlevels Is Nothing) Then
                _userlevels = MyBase.CreateObjectSet(Of userlevel)("userlevels")
            End If
            Return _userlevels
        End Get
    End Property

    Private _userlevels As ObjectSet(Of userlevel)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the departments EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTodepartments(ByVal department As department)
        MyBase.AddObject("departments", department)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ncrs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToncrs(ByVal ncr As ncr)
        MyBase.AddObject("ncrs", ncr)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the notifications EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTonotifications(ByVal notification As notification)
        MyBase.AddObject("notifications", notification)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTousers(ByVal user As user)
        MyBase.AddObject("users", user)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the userlevels EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTouserlevels(ByVal userlevel As userlevel)
        MyBase.AddObject("userlevels", userlevel)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rqtsModel", Name:="department")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class department
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new department object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    Public Shared Function Createdepartment(id As Global.System.Int32, description As Global.System.String) As department
        Dim department as department = New department
        department.id = id
        department.description = description
        Return department
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rqtsModel", Name:="ncr")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ncr
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ncr object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="raisedby_id">Initial value of the raisedby_id property.</param>
    ''' <param name="status_id">Initial value of the status_id property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    ''' <param name="title">Initial value of the title property.</param>
    Public Shared Function Createncr(id As Global.System.Int32, raisedby_id As Global.System.Int32, status_id As Global.System.Int32, description As Global.System.Byte(), title As Global.System.String) As ncr
        Dim ncr as ncr = New ncr
        ncr.id = id
        ncr.raisedby_id = raisedby_id
        ncr.status_id = status_id
        ncr.description = description
        ncr.title = title
        Return ncr
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property raisedby_id() As Global.System.Int32
        Get
            Return _raisedby_id
        End Get
        Set
            Onraisedby_idChanging(value)
            ReportPropertyChanging("raisedby_id")
            _raisedby_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("raisedby_id")
            Onraisedby_idChanged()
        End Set
    End Property

    Private _raisedby_id As Global.System.Int32
    Private Partial Sub Onraisedby_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onraisedby_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property assignedto_id() As Nullable(Of Global.System.Int32)
        Get
            Return _assignedto_id
        End Get
        Set
            Onassignedto_idChanging(value)
            ReportPropertyChanging("assignedto_id")
            _assignedto_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("assignedto_id")
            Onassignedto_idChanged()
        End Set
    End Property

    Private _assignedto_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onassignedto_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onassignedto_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property delegatedto_id() As Nullable(Of Global.System.Int32)
        Get
            Return _delegatedto_id
        End Get
        Set
            Ondelegatedto_idChanging(value)
            ReportPropertyChanging("delegatedto_id")
            _delegatedto_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delegatedto_id")
            Ondelegatedto_idChanged()
        End Set
    End Property

    Private _delegatedto_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Ondelegatedto_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Ondelegatedto_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property raiseddate() As Nullable(Of Global.System.DateTime)
        Get
            Return _raiseddate
        End Get
        Set
            OnraiseddateChanging(value)
            ReportPropertyChanging("raiseddate")
            _raiseddate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("raiseddate")
            OnraiseddateChanged()
        End Set
    End Property

    Private _raiseddate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnraiseddateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnraiseddateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status_id() As Global.System.Int32
        Get
            Return _status_id
        End Get
        Set
            Onstatus_idChanging(value)
            ReportPropertyChanging("status_id")
            _status_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("status_id")
            Onstatus_idChanged()
        End Set
    End Property

    Private _status_id As Global.System.Int32
    Private Partial Sub Onstatus_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstatus_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cc_id() As Nullable(Of Global.System.Int32)
        Get
            Return _cc_id
        End Get
        Set
            Oncc_idChanging(value)
            ReportPropertyChanging("cc_id")
            _cc_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cc_id")
            Oncc_idChanged()
        End Set
    End Property

    Private _cc_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncc_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncc_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property rcp_id() As Nullable(Of Global.System.Int32)
        Get
            Return _rcp_id
        End Get
        Set
            Onrcp_idChanging(value)
            ReportPropertyChanging("rcp_id")
            _rcp_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("rcp_id")
            Onrcp_idChanged()
        End Set
    End Property

    Private _rcp_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onrcp_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onrcp_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_description)
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.Byte()
    Private Partial Sub OndescriptionChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property title() As Global.System.String
        Get
            Return _title
        End Get
        Set
            OntitleChanging(value)
            ReportPropertyChanging("title")
            _title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("title")
            OntitleChanged()
        End Set
    End Property

    Private _title As Global.System.String
    Private Partial Sub OntitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntitleChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rqtsModel", Name:="notification")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class notification
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new notification object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="user_id">Initial value of the user_id property.</param>
    ''' <param name="ncr_id">Initial value of the ncr_id property.</param>
    ''' <param name="message">Initial value of the message property.</param>
    ''' <param name="timestamp">Initial value of the timestamp property.</param>
    Public Shared Function Createnotification(id As Global.System.Int32, user_id As Global.System.Int32, ncr_id As Global.System.Int32, message As Global.System.String, timestamp As Global.System.DateTime) As notification
        Dim notification as notification = New notification
        notification.id = id
        notification.user_id = user_id
        notification.ncr_id = ncr_id
        notification.message = message
        notification.timestamp = timestamp
        Return notification
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property user_id() As Global.System.Int32
        Get
            Return _user_id
        End Get
        Set
            Onuser_idChanging(value)
            ReportPropertyChanging("user_id")
            _user_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("user_id")
            Onuser_idChanged()
        End Set
    End Property

    Private _user_id As Global.System.Int32
    Private Partial Sub Onuser_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onuser_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ncr_id() As Global.System.Int32
        Get
            Return _ncr_id
        End Get
        Set
            Onncr_idChanging(value)
            ReportPropertyChanging("ncr_id")
            _ncr_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ncr_id")
            Onncr_idChanged()
        End Set
    End Property

    Private _ncr_id As Global.System.Int32
    Private Partial Sub Onncr_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onncr_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property message() As Global.System.String
        Get
            Return _message
        End Get
        Set
            OnmessageChanging(value)
            ReportPropertyChanging("message")
            _message = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("message")
            OnmessageChanged()
        End Set
    End Property

    Private _message As Global.System.String
    Private Partial Sub OnmessageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmessageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property timestamp() As Global.System.DateTime
        Get
            Return _timestamp
        End Get
        Set
            OntimestampChanging(value)
            ReportPropertyChanging("timestamp")
            _timestamp = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("timestamp")
            OntimestampChanged()
        End Set
    End Property

    Private _timestamp As Global.System.DateTime
    Private Partial Sub OntimestampChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OntimestampChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rqtsModel", Name:="user")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class user
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new user object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="firstname">Initial value of the firstname property.</param>
    ''' <param name="surname">Initial value of the surname property.</param>
    ''' <param name="userid">Initial value of the userid property.</param>
    ''' <param name="active">Initial value of the active property.</param>
    ''' <param name="level_id">Initial value of the level_id property.</param>
    ''' <param name="department_id">Initial value of the department_id property.</param>
    ''' <param name="password">Initial value of the password property.</param>
    ''' <param name="admin">Initial value of the admin property.</param>
    Public Shared Function Createuser(id As Global.System.Int32, firstname As Global.System.String, surname As Global.System.String, userid As Global.System.String, active As Global.System.SByte, level_id As Global.System.Int32, department_id As Global.System.Int32, password As Global.System.String, admin As Global.System.SByte) As user
        Dim user as user = New user
        user.id = id
        user.firstname = firstname
        user.surname = surname
        user.userid = userid
        user.active = active
        user.level_id = level_id
        user.department_id = department_id
        user.password = password
        user.admin = admin
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property firstname() As Global.System.String
        Get
            Return _firstname
        End Get
        Set
            OnfirstnameChanging(value)
            ReportPropertyChanging("firstname")
            _firstname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("firstname")
            OnfirstnameChanged()
        End Set
    End Property

    Private _firstname As Global.System.String
    Private Partial Sub OnfirstnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfirstnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property surname() As Global.System.String
        Get
            Return _surname
        End Get
        Set
            OnsurnameChanging(value)
            ReportPropertyChanging("surname")
            _surname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("surname")
            OnsurnameChanged()
        End Set
    End Property

    Private _surname As Global.System.String
    Private Partial Sub OnsurnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsurnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property userid() As Global.System.String
        Get
            Return _userid
        End Get
        Set
            OnuseridChanging(value)
            ReportPropertyChanging("userid")
            _userid = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("userid")
            OnuseridChanged()
        End Set
    End Property

    Private _userid As Global.System.String
    Private Partial Sub OnuseridChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnuseridChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property email() As Global.System.String
        Get
            Return _email
        End Get
        Set
            OnemailChanging(value)
            ReportPropertyChanging("email")
            _email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("email")
            OnemailChanged()
        End Set
    End Property

    Private _email As Global.System.String
    Private Partial Sub OnemailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnemailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property active() As Global.System.SByte
        Get
            Return _active
        End Get
        Set
            OnactiveChanging(value)
            ReportPropertyChanging("active")
            _active = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("active")
            OnactiveChanged()
        End Set
    End Property

    Private _active As Global.System.SByte
    Private Partial Sub OnactiveChanging(value As Global.System.SByte)
    End Sub

    Private Partial Sub OnactiveChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property level_id() As Global.System.Int32
        Get
            Return _level_id
        End Get
        Set
            Onlevel_idChanging(value)
            ReportPropertyChanging("level_id")
            _level_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("level_id")
            Onlevel_idChanged()
        End Set
    End Property

    Private _level_id As Global.System.Int32
    Private Partial Sub Onlevel_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onlevel_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property department_id() As Global.System.Int32
        Get
            Return _department_id
        End Get
        Set
            Ondepartment_idChanging(value)
            ReportPropertyChanging("department_id")
            _department_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("department_id")
            Ondepartment_idChanged()
        End Set
    End Property

    Private _department_id As Global.System.Int32
    Private Partial Sub Ondepartment_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondepartment_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property admin() As Global.System.SByte
        Get
            Return _admin
        End Get
        Set
            OnadminChanging(value)
            ReportPropertyChanging("admin")
            _admin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("admin")
            OnadminChanged()
        End Set
    End Property

    Private _admin As Global.System.SByte
    Private Partial Sub OnadminChanging(value As Global.System.SByte)
    End Sub

    Private Partial Sub OnadminChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usercol() As Global.System.String
        Get
            Return _usercol
        End Get
        Set
            OnusercolChanging(value)
            ReportPropertyChanging("usercol")
            _usercol = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usercol")
            OnusercolChanged()
        End Set
    End Property

    Private _usercol As Global.System.String
    Private Partial Sub OnusercolChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusercolChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="rqtsModel", Name:="userlevel")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class userlevel
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new userlevel object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createuserlevel(id As Global.System.Int32) As userlevel
        Dim userlevel as userlevel = New userlevel
        userlevel.id = id
        Return userlevel
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fulldescription() As Global.System.String
        Get
            Return _fulldescription
        End Get
        Set
            OnfulldescriptionChanging(value)
            ReportPropertyChanging("fulldescription")
            _fulldescription = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fulldescription")
            OnfulldescriptionChanged()
        End Set
    End Property

    Private _fulldescription As Global.System.String
    Private Partial Sub OnfulldescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfulldescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property shortdescription() As Global.System.String
        Get
            Return _shortdescription
        End Get
        Set
            OnshortdescriptionChanging(value)
            ReportPropertyChanging("shortdescription")
            _shortdescription = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("shortdescription")
            OnshortdescriptionChanged()
        End Set
    End Property

    Private _shortdescription As Global.System.String
    Private Partial Sub OnshortdescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnshortdescriptionChanged()
    End Sub

    #End Region

End Class

#End Region


