
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("59029b1d-0cef-485a-82b2-59864a3818ac")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("BaseModel", "userleveluser", "userlevel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Userlevel), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(User), True)>
<Assembly: EdmRelationshipAttribute("BaseModel", "departmentuser", "department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Department), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(User), True)>
<Assembly: EdmRelationshipAttribute("BaseModel", "ncruser", "ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Ncr), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(User), True)>
<Assembly: EdmRelationshipAttribute("BaseModel", "raisedby", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(User), "ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Ncr), True)>
<Assembly: EdmRelationshipAttribute("BaseModel", "owner", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(User), "delegate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Ncr), True)>
<Assembly: EdmRelationshipAttribute("BaseModel", "cc_ccitem", "cc", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(cc), "ccitem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ccitem), True)>
<Assembly: EdmRelationshipAttribute("BaseModel", "Ncrcc", "Ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Ncr), "cc", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(cc), True)>
<Assembly: EdmRelationshipAttribute("BaseModel", "OwnerAssociation", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(User), "Ncr", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Ncr), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class rqtsEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new rqtsEntities object using the connection string found in the 'rqtsEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=rqtsEntities", "rqtsEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rqtsEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "rqtsEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new rqtsEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "rqtsEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Departments() As ObjectSet(Of Department)
        Get
            If (_Departments Is Nothing) Then
                _Departments = MyBase.CreateObjectSet(Of Department)("Departments")
            End If
            Return _Departments
        End Get
    End Property

    Private _Departments As ObjectSet(Of Department)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Ncrs() As ObjectSet(Of Ncr)
        Get
            If (_Ncrs Is Nothing) Then
                _Ncrs = MyBase.CreateObjectSet(Of Ncr)("Ncrs")
            End If
            Return _Ncrs
        End Get
    End Property

    Private _Ncrs As ObjectSet(Of Ncr)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Notifications() As ObjectSet(Of Notification)
        Get
            If (_Notifications Is Nothing) Then
                _Notifications = MyBase.CreateObjectSet(Of Notification)("Notifications")
            End If
            Return _Notifications
        End Get
    End Property

    Private _Notifications As ObjectSet(Of Notification)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Users() As ObjectSet(Of User)
        Get
            If (_Users Is Nothing) Then
                _Users = MyBase.CreateObjectSet(Of User)("Users")
            End If
            Return _Users
        End Get
    End Property

    Private _Users As ObjectSet(Of User)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Userlevels() As ObjectSet(Of Userlevel)
        Get
            If (_Userlevels Is Nothing) Then
                _Userlevels = MyBase.CreateObjectSet(Of Userlevel)("Userlevels")
            End If
            Return _Userlevels
        End Get
    End Property

    Private _Userlevels As ObjectSet(Of Userlevel)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ccitems() As ObjectSet(Of ccitem)
        Get
            If (_ccitems Is Nothing) Then
                _ccitems = MyBase.CreateObjectSet(Of ccitem)("ccitems")
            End If
            Return _ccitems
        End Get
    End Property

    Private _ccitems As ObjectSet(Of ccitem)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property cc() As ObjectSet(Of cc)
        Get
            If (_cc Is Nothing) Then
                _cc = MyBase.CreateObjectSet(Of cc)("cc")
            End If
            Return _cc
        End Get
    End Property

    Private _cc As ObjectSet(Of cc)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property logs() As ObjectSet(Of log)
        Get
            If (_logs Is Nothing) Then
                _logs = MyBase.CreateObjectSet(Of log)("logs")
            End If
            Return _logs
        End Get
    End Property

    Private _logs As ObjectSet(Of log)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Departments EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDepartments(ByVal department As Department)
        MyBase.AddObject("Departments", department)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Ncrs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToNcrs(ByVal ncr As Ncr)
        MyBase.AddObject("Ncrs", ncr)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Notifications EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToNotifications(ByVal notification As Notification)
        MyBase.AddObject("Notifications", notification)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUsers(ByVal user As User)
        MyBase.AddObject("Users", user)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Userlevels EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUserlevels(ByVal userlevel As Userlevel)
        MyBase.AddObject("Userlevels", userlevel)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ccitems EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToccitems(ByVal ccitem As ccitem)
        MyBase.AddObject("ccitems", ccitem)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the cc EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTocc(ByVal cc As cc)
        MyBase.AddObject("cc", cc)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the logs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTologs(ByVal log As log)
        MyBase.AddObject("logs", log)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="cc")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class cc
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new cc object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="owner_id">Initial value of the owner_id property.</param>
    Public Shared Function Createcc(id As Global.System.Int32, owner_id As Global.System.Int32) As cc
        Dim cc as cc = New cc
        cc.id = id
        cc.owner_id = owner_id
        Return cc
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property planapprover_id() As Nullable(Of Global.System.Int32)
        Get
            Return _planapprover_id
        End Get
        Set
            Onplanapprover_idChanging(value)
            ReportPropertyChanging("planapprover_id")
            _planapprover_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("planapprover_id")
            Onplanapprover_idChanged()
        End Set
    End Property

    Private _planapprover_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onplanapprover_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onplanapprover_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property planapprovedate() As Nullable(Of Global.System.DateTime)
        Get
            Return _planapprovedate
        End Get
        Set
            OnplanapprovedateChanging(value)
            ReportPropertyChanging("planapprovedate")
            _planapprovedate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("planapprovedate")
            OnplanapprovedateChanged()
        End Set
    End Property

    Private _planapprovedate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnplanapprovedateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnplanapprovedateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property completiondate() As Nullable(Of Global.System.DateTime)
        Get
            Return _completiondate
        End Get
        Set
            OncompletiondateChanging(value)
            ReportPropertyChanging("completiondate")
            _completiondate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("completiondate")
            OncompletiondateChanged()
        End Set
    End Property

    Private _completiondate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OncompletiondateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OncompletiondateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property solutionverifier_id() As Nullable(Of Global.System.Int32)
        Get
            Return _solutionverifier_id
        End Get
        Set
            Onsolutionverifier_idChanging(value)
            ReportPropertyChanging("solutionverifier_id")
            _solutionverifier_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("solutionverifier_id")
            Onsolutionverifier_idChanged()
        End Set
    End Property

    Private _solutionverifier_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onsolutionverifier_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onsolutionverifier_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property closedate() As Nullable(Of Global.System.DateTime)
        Get
            Return _closedate
        End Get
        Set
            OnclosedateChanging(value)
            ReportPropertyChanging("closedate")
            _closedate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("closedate")
            OnclosedateChanged()
        End Set
    End Property

    Private _closedate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnclosedateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnclosedateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status_id() As Global.System.Int32
        Get
            Return _status_id
        End Get
        Set
            Onstatus_idChanging(value)
            ReportPropertyChanging("status_id")
            _status_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("status_id")
            Onstatus_idChanged()
        End Set
    End Property

    Private _status_id As Global.System.Int32 = 0
    Private Partial Sub Onstatus_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstatus_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property owner_id() As Global.System.Int32
        Get
            Return _owner_id
        End Get
        Set
            Onowner_idChanging(value)
            ReportPropertyChanging("owner_id")
            _owner_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("owner_id")
            Onowner_idChanged()
        End Set
    End Property

    Private _owner_id As Global.System.Int32
    Private Partial Sub Onowner_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onowner_idChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "cc_ccitem", "ccitem")>
     Public Property ccitems() As EntityCollection(Of ccitem)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ccitem)("BaseModel.cc_ccitem", "ccitem")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ccitem)("BaseModel.cc_ccitem", "ccitem", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "Ncrcc", "Ncr")>
    Public Property Ncr() As Ncr
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ncr)("BaseModel.Ncrcc", "Ncr").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ncr)("BaseModel.Ncrcc", "Ncr").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property NcrReference() As EntityReference(Of Ncr)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Ncr)("BaseModel.Ncrcc", "Ncr")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Ncr)("BaseModel.Ncrcc", "Ncr", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="ccitem")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ccitem
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ccitem object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="action">Initial value of the action property.</param>
    ''' <param name="actionby_id">Initial value of the actionby_id property.</param>
    ''' <param name="duedate">Initial value of the duedate property.</param>
    ''' <param name="status">Initial value of the status property.</param>
    ''' <param name="cc_id">Initial value of the cc_id property.</param>
    Public Shared Function Createccitem(id As Global.System.Int32, action As Global.System.String, actionby_id As Global.System.Int32, duedate As Global.System.DateTime, status As Global.System.String, cc_id As Global.System.Int32) As ccitem
        Dim ccitem as ccitem = New ccitem
        ccitem.id = id
        ccitem.action = action
        ccitem.actionby_id = actionby_id
        ccitem.duedate = duedate
        ccitem.status = status
        ccitem.cc_id = cc_id
        Return ccitem
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property action() As Global.System.String
        Get
            Return _action
        End Get
        Set
            OnactionChanging(value)
            ReportPropertyChanging("action")
            _action = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("action")
            OnactionChanged()
        End Set
    End Property

    Private _action As Global.System.String
    Private Partial Sub OnactionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnactionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property actionby_id() As Global.System.Int32
        Get
            Return _actionby_id
        End Get
        Set
            Onactionby_idChanging(value)
            ReportPropertyChanging("actionby_id")
            _actionby_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("actionby_id")
            Onactionby_idChanged()
        End Set
    End Property

    Private _actionby_id As Global.System.Int32
    Private Partial Sub Onactionby_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onactionby_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property duedate() As Global.System.DateTime
        Get
            Return _duedate
        End Get
        Set
            OnduedateChanging(value)
            ReportPropertyChanging("duedate")
            _duedate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("duedate")
            OnduedateChanged()
        End Set
    End Property

    Private _duedate As Global.System.DateTime
    Private Partial Sub OnduedateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnduedateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property completiondate() As Nullable(Of Global.System.DateTime)
        Get
            Return _completiondate
        End Get
        Set
            OncompletiondateChanging(value)
            ReportPropertyChanging("completiondate")
            _completiondate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("completiondate")
            OncompletiondateChanged()
        End Set
    End Property

    Private _completiondate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OncompletiondateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OncompletiondateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status() As Global.System.String
        Get
            Return _status
        End Get
        Set
            OnstatusChanging(value)
            ReportPropertyChanging("status")
            _status = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("status")
            OnstatusChanged()
        End Set
    End Property

    Private _status As Global.System.String
    Private Partial Sub OnstatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cc_id() As Global.System.Int32
        Get
            Return _cc_id
        End Get
        Set
            Oncc_idChanging(value)
            ReportPropertyChanging("cc_id")
            _cc_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cc_id")
            Oncc_idChanged()
        End Set
    End Property

    Private _cc_id As Global.System.Int32
    Private Partial Sub Oncc_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Oncc_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property passed() As Nullable(Of Global.System.Boolean)
        Get
            Return _passed
        End Get
        Set
            OnpassedChanging(value)
            ReportPropertyChanging("passed")
            _passed = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("passed")
            OnpassedChanged()
        End Set
    End Property

    Private _passed As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnpassedChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnpassedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property failed() As Nullable(Of Global.System.Boolean)
        Get
            Return _failed
        End Get
        Set
            OnfailedChanging(value)
            ReportPropertyChanging("failed")
            _failed = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("failed")
            OnfailedChanged()
        End Set
    End Property

    Private _failed As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnfailedChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnfailedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property reviewer_id() As Nullable(Of Global.System.Int32)
        Get
            Return _reviewer_id
        End Get
        Set
            Onreviewer_idChanging(value)
            ReportPropertyChanging("reviewer_id")
            _reviewer_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("reviewer_id")
            Onreviewer_idChanged()
        End Set
    End Property

    Private _reviewer_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onreviewer_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onreviewer_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property reviewdate() As Nullable(Of Global.System.DateTime)
        Get
            Return _reviewdate
        End Get
        Set
            OnreviewdateChanging(value)
            ReportPropertyChanging("reviewdate")
            _reviewdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("reviewdate")
            OnreviewdateChanged()
        End Set
    End Property

    Private _reviewdate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnreviewdateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnreviewdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property reviewcomment() As Global.System.String
        Get
            Return _reviewcomment
        End Get
        Set
            OnreviewcommentChanging(value)
            ReportPropertyChanging("reviewcomment")
            _reviewcomment = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("reviewcomment")
            OnreviewcommentChanged()
        End Set
    End Property

    Private _reviewcomment As Global.System.String
    Private Partial Sub OnreviewcommentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnreviewcommentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property seq() As Nullable(Of Global.System.Int32)
        Get
            Return _seq
        End Get
        Set
            OnseqChanging(value)
            ReportPropertyChanging("seq")
            _seq = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("seq")
            OnseqChanged()
        End Set
    End Property

    Private _seq As Nullable(Of Global.System.Int32)
    Private Partial Sub OnseqChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnseqChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "cc_ccitem", "cc")>
    Public Property cc() As cc
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of cc)("BaseModel.cc_ccitem", "cc").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of cc)("BaseModel.cc_ccitem", "cc").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ccReference() As EntityReference(Of cc)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of cc)("BaseModel.cc_ccitem", "cc")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of cc)("BaseModel.cc_ccitem", "cc", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="Department")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Department
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Department object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    Public Shared Function CreateDepartment(id As Global.System.Int32, description As Global.System.String) As Department
        Dim department as Department = New Department
        department.id = id
        department.description = description
        Return department
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "departmentuser", "user")>
     Public Property users() As EntityCollection(Of User)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of User)("BaseModel.departmentuser", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of User)("BaseModel.departmentuser", "user", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="log")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class log
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new log object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="timestamp">Initial value of the timestamp property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    ''' <param name="ncr_id">Initial value of the ncr_id property.</param>
    Public Shared Function Createlog(id As Global.System.Int32, timestamp As Global.System.DateTime, description As Global.System.String, ncr_id As Global.System.Int32) As log
        Dim log as log = New log
        log.id = id
        log.timestamp = timestamp
        log.description = description
        log.ncr_id = ncr_id
        Return log
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property timestamp() As Global.System.DateTime
        Get
            Return _timestamp
        End Get
        Set
            OntimestampChanging(value)
            ReportPropertyChanging("timestamp")
            _timestamp = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("timestamp")
            OntimestampChanged()
        End Set
    End Property

    Private _timestamp As Global.System.DateTime
    Private Partial Sub OntimestampChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OntimestampChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ncr_id() As Global.System.Int32
        Get
            Return _ncr_id
        End Get
        Set
            Onncr_idChanging(value)
            ReportPropertyChanging("ncr_id")
            _ncr_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ncr_id")
            Onncr_idChanged()
        End Set
    End Property

    Private _ncr_id As Global.System.Int32
    Private Partial Sub Onncr_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onncr_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property user_id() As Nullable(Of Global.System.Int32)
        Get
            Return _user_id
        End Get
        Set
            Onuser_idChanging(value)
            ReportPropertyChanging("user_id")
            _user_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("user_id")
            Onuser_idChanged()
        End Set
    End Property

    Private _user_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onuser_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onuser_idChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="Ncr")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Ncr
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Ncr object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="raisedby_id">Initial value of the raisedby_id property.</param>
    ''' <param name="status_id">Initial value of the status_id property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    ''' <param name="title">Initial value of the title property.</param>
    ''' <param name="owner_id">Initial value of the owner_id property.</param>
    Public Shared Function CreateNcr(id As Global.System.Int32, raisedby_id As Global.System.Int32, status_id As Global.System.Int32, description As Global.System.String, title As Global.System.String, owner_id As Global.System.Int32) As Ncr
        Dim ncr as Ncr = New Ncr
        ncr.id = id
        ncr.raisedby_id = raisedby_id
        ncr.status_id = status_id
        ncr.description = description
        ncr.title = title
        ncr.owner_id = owner_id
        Return ncr
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property raisedby_id() As Global.System.Int32
        Get
            Return _raisedby_id
        End Get
        Set
            Onraisedby_idChanging(value)
            ReportPropertyChanging("raisedby_id")
            _raisedby_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("raisedby_id")
            Onraisedby_idChanged()
        End Set
    End Property

    Private _raisedby_id As Global.System.Int32
    Private Partial Sub Onraisedby_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onraisedby_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property assignedto_id() As Nullable(Of Global.System.Int32)
        Get
            Return _assignedto_id
        End Get
        Set
            Onassignedto_idChanging(value)
            ReportPropertyChanging("assignedto_id")
            _assignedto_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("assignedto_id")
            Onassignedto_idChanged()
        End Set
    End Property

    Private _assignedto_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onassignedto_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onassignedto_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property delegatedto_id() As Nullable(Of Global.System.Int32)
        Get
            Return _delegatedto_id
        End Get
        Set
            Ondelegatedto_idChanging(value)
            ReportPropertyChanging("delegatedto_id")
            _delegatedto_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delegatedto_id")
            Ondelegatedto_idChanged()
        End Set
    End Property

    Private _delegatedto_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Ondelegatedto_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Ondelegatedto_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property raiseddate() As Nullable(Of Global.System.DateTime)
        Get
            Return _raiseddate
        End Get
        Set
            OnraiseddateChanging(value)
            ReportPropertyChanging("raiseddate")
            _raiseddate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("raiseddate")
            OnraiseddateChanged()
        End Set
    End Property

    Private _raiseddate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnraiseddateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnraiseddateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status_id() As Global.System.Int32
        Get
            Return _status_id
        End Get
        Set
            Onstatus_idChanging(value)
            ReportPropertyChanging("status_id")
            _status_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("status_id")
            Onstatus_idChanged()
        End Set
    End Property

    Private _status_id As Global.System.Int32
    Private Partial Sub Onstatus_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstatus_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cc_id() As Nullable(Of Global.System.Int32)
        Get
            Return _cc_id
        End Get
        Set
            Oncc_idChanging(value)
            ReportPropertyChanging("cc_id")
            _cc_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cc_id")
            Oncc_idChanged()
        End Set
    End Property

    Private _cc_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncc_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncc_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property rcp_id() As Nullable(Of Global.System.Int32)
        Get
            Return _rcp_id
        End Get
        Set
            Onrcp_idChanging(value)
            ReportPropertyChanging("rcp_id")
            _rcp_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("rcp_id")
            Onrcp_idChanged()
        End Set
    End Property

    Private _rcp_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onrcp_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onrcp_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property title() As Global.System.String
        Get
            Return _title
        End Get
        Set
            OntitleChanging(value)
            ReportPropertyChanging("title")
            _title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("title")
            OntitleChanged()
        End Set
    End Property

    Private _title As Global.System.String
    Private Partial Sub OntitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property owner_id() As Global.System.Int32
        Get
            Return _owner_id
        End Get
        Set
            Onowner_idChanging(value)
            ReportPropertyChanging("owner_id")
            _owner_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("owner_id")
            Onowner_idChanged()
        End Set
    End Property

    Private _owner_id As Global.System.Int32
    Private Partial Sub Onowner_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onowner_idChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "ncruser", "user")>
    Public Property AssignedTo() As User
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.ncruser", "user").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.ncruser", "user").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AssignedToReference() As EntityReference(Of User)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.ncruser", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("BaseModel.ncruser", "user", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "raisedby", "user")>
    Public Property RaisedBy() As User
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.raisedby", "user").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.raisedby", "user").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property RaisedByReference() As EntityReference(Of User)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.raisedby", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("BaseModel.raisedby", "user", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "owner", "user")>
    Public Property [Delegate]() As User
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.owner", "user").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.owner", "user").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DelegateReference() As EntityReference(Of User)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.owner", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("BaseModel.owner", "user", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "Ncrcc", "cc")>
    Public Property cc() As cc
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of cc)("BaseModel.Ncrcc", "cc").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of cc)("BaseModel.Ncrcc", "cc").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ccReference() As EntityReference(Of cc)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of cc)("BaseModel.Ncrcc", "cc")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of cc)("BaseModel.Ncrcc", "cc", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "OwnerAssociation", "User")>
    Public Property OwnerUser() As User
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.OwnerAssociation", "User").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.OwnerAssociation", "User").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OwnerUserReference() As EntityReference(Of User)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BaseModel.OwnerAssociation", "User")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("BaseModel.OwnerAssociation", "User", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="Notification")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Notification
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Notification object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="user_id">Initial value of the user_id property.</param>
    ''' <param name="ncr_id">Initial value of the ncr_id property.</param>
    ''' <param name="message">Initial value of the message property.</param>
    ''' <param name="timestamp">Initial value of the timestamp property.</param>
    Public Shared Function CreateNotification(id As Global.System.Int32, user_id As Global.System.Int32, ncr_id As Global.System.Int32, message As Global.System.String, timestamp As Global.System.DateTime) As Notification
        Dim notification as Notification = New Notification
        notification.id = id
        notification.user_id = user_id
        notification.ncr_id = ncr_id
        notification.message = message
        notification.timestamp = timestamp
        Return notification
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property user_id() As Global.System.Int32
        Get
            Return _user_id
        End Get
        Set
            Onuser_idChanging(value)
            ReportPropertyChanging("user_id")
            _user_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("user_id")
            Onuser_idChanged()
        End Set
    End Property

    Private _user_id As Global.System.Int32
    Private Partial Sub Onuser_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onuser_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ncr_id() As Global.System.Int32
        Get
            Return _ncr_id
        End Get
        Set
            Onncr_idChanging(value)
            ReportPropertyChanging("ncr_id")
            _ncr_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ncr_id")
            Onncr_idChanged()
        End Set
    End Property

    Private _ncr_id As Global.System.Int32
    Private Partial Sub Onncr_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onncr_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property message() As Global.System.String
        Get
            Return _message
        End Get
        Set
            OnmessageChanging(value)
            ReportPropertyChanging("message")
            _message = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("message")
            OnmessageChanged()
        End Set
    End Property

    Private _message As Global.System.String
    Private Partial Sub OnmessageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmessageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property timestamp() As Global.System.DateTime
        Get
            Return _timestamp
        End Get
        Set
            OntimestampChanging(value)
            ReportPropertyChanging("timestamp")
            _timestamp = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("timestamp")
            OntimestampChanged()
        End Set
    End Property

    Private _timestamp As Global.System.DateTime
    Private Partial Sub OntimestampChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OntimestampChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="User")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class User
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new User object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="firstname">Initial value of the firstname property.</param>
    ''' <param name="surname">Initial value of the surname property.</param>
    ''' <param name="userid">Initial value of the userid property.</param>
    ''' <param name="active">Initial value of the active property.</param>
    ''' <param name="level_id">Initial value of the level_id property.</param>
    ''' <param name="department_id">Initial value of the department_id property.</param>
    ''' <param name="password">Initial value of the password property.</param>
    ''' <param name="admin">Initial value of the admin property.</param>
    Public Shared Function CreateUser(id As Global.System.Int32, firstname As Global.System.String, surname As Global.System.String, userid As Global.System.String, active As Global.System.SByte, level_id As Global.System.Int32, department_id As Global.System.Int32, password As Global.System.String, admin As Global.System.SByte) As User
        Dim user as User = New User
        user.id = id
        user.firstname = firstname
        user.surname = surname
        user.userid = userid
        user.active = active
        user.level_id = level_id
        user.department_id = department_id
        user.password = password
        user.admin = admin
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property firstname() As Global.System.String
        Get
            Return _firstname
        End Get
        Set
            OnfirstnameChanging(value)
            ReportPropertyChanging("firstname")
            _firstname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("firstname")
            OnfirstnameChanged()
        End Set
    End Property

    Private _firstname As Global.System.String
    Private Partial Sub OnfirstnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfirstnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property surname() As Global.System.String
        Get
            Return _surname
        End Get
        Set
            OnsurnameChanging(value)
            ReportPropertyChanging("surname")
            _surname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("surname")
            OnsurnameChanged()
        End Set
    End Property

    Private _surname As Global.System.String
    Private Partial Sub OnsurnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsurnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property userid() As Global.System.String
        Get
            Return _userid
        End Get
        Set
            OnuseridChanging(value)
            ReportPropertyChanging("userid")
            _userid = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("userid")
            OnuseridChanged()
        End Set
    End Property

    Private _userid As Global.System.String
    Private Partial Sub OnuseridChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnuseridChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property email() As Global.System.String
        Get
            Return _email
        End Get
        Set
            OnemailChanging(value)
            ReportPropertyChanging("email")
            _email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("email")
            OnemailChanged()
        End Set
    End Property

    Private _email As Global.System.String
    Private Partial Sub OnemailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnemailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property active() As Global.System.SByte
        Get
            Return _active
        End Get
        Set
            OnactiveChanging(value)
            ReportPropertyChanging("active")
            _active = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("active")
            OnactiveChanged()
        End Set
    End Property

    Private _active As Global.System.SByte
    Private Partial Sub OnactiveChanging(value As Global.System.SByte)
    End Sub

    Private Partial Sub OnactiveChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property level_id() As Global.System.Int32
        Get
            Return _level_id
        End Get
        Set
            Onlevel_idChanging(value)
            ReportPropertyChanging("level_id")
            _level_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("level_id")
            Onlevel_idChanged()
        End Set
    End Property

    Private _level_id As Global.System.Int32
    Private Partial Sub Onlevel_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onlevel_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property department_id() As Global.System.Int32
        Get
            Return _department_id
        End Get
        Set
            Ondepartment_idChanging(value)
            ReportPropertyChanging("department_id")
            _department_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("department_id")
            Ondepartment_idChanged()
        End Set
    End Property

    Private _department_id As Global.System.Int32
    Private Partial Sub Ondepartment_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondepartment_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property admin() As Global.System.SByte
        Get
            Return _admin
        End Get
        Set
            OnadminChanging(value)
            ReportPropertyChanging("admin")
            _admin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("admin")
            OnadminChanged()
        End Set
    End Property

    Private _admin As Global.System.SByte
    Private Partial Sub OnadminChanging(value As Global.System.SByte)
    End Sub

    Private Partial Sub OnadminChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "userleveluser", "userlevel")>
    Public Property userlevel() As Userlevel
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Userlevel)("BaseModel.userleveluser", "userlevel").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Userlevel)("BaseModel.userleveluser", "userlevel").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property userlevelReference() As EntityReference(Of Userlevel)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Userlevel)("BaseModel.userleveluser", "userlevel")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Userlevel)("BaseModel.userleveluser", "userlevel", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "departmentuser", "department")>
    Public Property department() As Department
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Department)("BaseModel.departmentuser", "department").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Department)("BaseModel.departmentuser", "department").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property departmentReference() As EntityReference(Of Department)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Department)("BaseModel.departmentuser", "department")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Department)("BaseModel.departmentuser", "department", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "ncruser", "ncr")>
     Public Property assigned() As EntityCollection(Of Ncr)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Ncr)("BaseModel.ncruser", "ncr")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Ncr)("BaseModel.ncruser", "ncr", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "OwnerAssociation", "Ncr")>
     Public Property Ncrs() As EntityCollection(Of Ncr)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Ncr)("BaseModel.OwnerAssociation", "Ncr")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Ncr)("BaseModel.OwnerAssociation", "Ncr", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BaseModel", Name:="Userlevel")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Userlevel
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Userlevel object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function CreateUserlevel(id As Global.System.Int32) As Userlevel
        Dim userlevel as Userlevel = New Userlevel
        userlevel.id = id
        Return userlevel
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fulldescription() As Global.System.String
        Get
            Return _fulldescription
        End Get
        Set
            OnfulldescriptionChanging(value)
            ReportPropertyChanging("fulldescription")
            _fulldescription = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fulldescription")
            OnfulldescriptionChanged()
        End Set
    End Property

    Private _fulldescription As Global.System.String
    Private Partial Sub OnfulldescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfulldescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property shortdescription() As Global.System.String
        Get
            Return _shortdescription
        End Get
        Set
            OnshortdescriptionChanging(value)
            ReportPropertyChanging("shortdescription")
            _shortdescription = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("shortdescription")
            OnshortdescriptionChanged()
        End Set
    End Property

    Private _shortdescription As Global.System.String
    Private Partial Sub OnshortdescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnshortdescriptionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BaseModel", "userleveluser", "user")>
     Public Property users() As EntityCollection(Of User)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of User)("BaseModel.userleveluser", "user")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of User)("BaseModel.userleveluser", "user", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


